version: '3'
services:
  web1:
    image: tomcat:latest
    ports:
      - 8081:8080
    container_name: tomcat-web1
    volumes:
      - ./index.html:/etc/nginx

  web2:
    image: tomcat:latest
    ports:
      - 8082:8080
    container_name: tomcat-web2
    volumes:
      - ./index.html:/etc/nginx
