version: '3'
services:
  web1:
    image: tomcat:latest
    ports:
      - 8081:8080
    container_name: tomcat-web1
    volumes:
      - ./index.html:/usr/local/tomcat/webapps/ROOT/index.jsp
    command: mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps

  web2:
    image: tomcat:latest
    ports:
      - 8082:8080
    container_name: tomcat-web2
    volumes:
      - ./index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
    command: mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps
